import { AIAChannel } from './types';

export const AIA_CHANNELS: AIAChannel[] = [
  {
    wavelength: 4500,
    sourceId: 17,
    layer: '[SDO,AIA,AIA,4500,1,100]',
    name: 'Visible Continuum',
    colour: '#F5E6C8',
    falseName: 'Yellow',
    temperature: '5,700\u00B0C',
    temperatureK: 5700,
    region: 'Photosphere',
    description: 'The surface. Sunspots appear as dark patches where magnetic fields suppress convection.',
    reveals: 'Sunspots, granulation, limb darkening',
    ion: 'Continuum (white light)',
  },
  {
    wavelength: 1700,
    sourceId: 16,
    layer: '[SDO,AIA,AIA,1700,1,100]',
    name: 'UV Continuum',
    colour: '#E8B0D4',
    falseName: 'Pink',
    temperature: '4,500\u00B0C',
    temperatureK: 4500,
    region: 'Photosphere / low Chromosphere',
    description: 'Just above the surface. Shows where magnetic field lines are concentrated \u2014 a web of bright network patterns.',
    reveals: 'Magnetic network, plage, sunspot penumbrae',
    ion: 'Continuum',
  },
  {
    wavelength: 1600,
    sourceId: 15,
    layer: '[SDO,AIA,AIA,1600,1,100]',
    name: 'Far UV',
    colour: '#C8D850',
    falseName: 'Green-yellow',
    temperature: '10,000\u00B0C & 100,000\u00B0C',
    temperatureK: 100000,
    region: 'Upper Photosphere / Transition Region',
    description: 'A mixture of two layers. The transition region is where temperature starts rising dramatically \u2014 from thousands to millions of degrees in a thin shell.',
    reveals: 'Transition region brightenings, UV flare ribbons',
    ion: 'C IV',
  },
  {
    wavelength: 304,
    sourceId: 13,
    layer: '[SDO,AIA,AIA,304,1,100]',
    name: 'He II',
    colour: '#FF6030',
    falseName: 'Orange',
    temperature: '50,000\u00B0C',
    temperatureK: 50000,
    region: 'Chromosphere / Transition Region',
    description: 'The chromosphere \u2014 the Sun\'s "atmosphere" just above the surface. Filaments and prominences are vivid here, arching above the limb.',
    reveals: 'Prominences, filaments, chromospheric network, spicules',
    ion: 'He II (ionised helium)',
  },
  {
    wavelength: 171,
    sourceId: 10,
    layer: '[SDO,AIA,AIA,171,1,100]',
    name: 'Fe IX',
    colour: '#FFD700',
    falseName: 'Gold',
    temperature: '630,000\u00B0C',
    temperatureK: 630000,
    region: 'Quiet Corona',
    description: 'The quiet corona \u2014 the Sun\'s outer atmosphere. Beautiful magnetic loops arch between regions of opposite polarity, tracing the magnetic field like iron filings.',
    reveals: 'Coronal loops, active region structure, coronal rain',
    ion: 'Fe IX (8\u00D7 ionised iron)',
  },
  {
    wavelength: 193,
    sourceId: 11,
    layer: '[SDO,AIA,AIA,193,1,100]',
    name: 'Fe XII / XXIV',
    colour: '#C89650',
    falseName: 'Bronze',
    temperature: '1,200,000\u00B0C (& 20,000,000\u00B0C)',
    temperatureK: 1200000,
    region: 'Corona / Flare Plasma',
    description: 'The hot corona. Coronal holes \u2014 dark regions where the magnetic field opens into space \u2014 become dramatically visible. These are the source of the solar wind.',
    reveals: 'Coronal holes, hot active regions, CME fronts, solar wind source',
    ion: 'Fe XII, Fe XXIV',
  },
  {
    wavelength: 211,
    sourceId: 12,
    layer: '[SDO,AIA,AIA,211,1,100]',
    name: 'Fe XIV',
    colour: '#8040C0',
    falseName: 'Violet',
    temperature: '2,000,000\u00B0C',
    temperatureK: 2000000,
    region: 'Active Corona',
    description: 'Magnetically active regions glow bright. The temperature here is 350\u00D7 the Sun\'s surface. This is the "working temperature" of the corona \u2014 where most coronal heating mystery research focuses.',
    reveals: 'Active regions, hot loops, coronal bright points',
    ion: 'Fe XIV (13\u00D7 ionised iron)',
  },
  {
    wavelength: 335,
    sourceId: 14,
    layer: '[SDO,AIA,AIA,335,1,100]',
    name: 'Fe XVI',
    colour: '#4060E0',
    falseName: 'Blue',
    temperature: '2,500,000\u00B0C',
    temperatureK: 2500000,
    region: 'Active Corona',
    description: 'Even hotter plasma in the active corona. This channel and 211\u00C5 together reveal the structure of the hottest coronal loops.',
    reveals: 'Hot loops, active region cores, sigmoid structures',
    ion: 'Fe XVI (15\u00D7 ionised iron)',
  },
  {
    wavelength: 94,
    sourceId: 8,
    layer: '[SDO,AIA,AIA,94,1,100]',
    name: 'Fe XVIII',
    colour: '#30C030',
    falseName: 'Green',
    temperature: '6,300,000\u00B0C',
    temperatureK: 6300000,
    region: 'Flare Plasma',
    description: 'Only the most extreme events show up here \u2014 solar flares at 6 million degrees. During a flare, ribbons of light blaze in this channel that are invisible everywhere else.',
    reveals: 'Solar flares, hot plasma sheets, post-flare loops',
    ion: 'Fe XVIII (17\u00D7 ionised iron)',
  },
  {
    wavelength: 131,
    sourceId: 9,
    layer: '[SDO,AIA,AIA,131,1,100]',
    name: 'Fe VIII / XXI',
    colour: '#30C0C0',
    falseName: 'Aqua',
    temperature: '400,000\u00B0C & 10,000,000\u00B0C',
    temperatureK: 10000000,
    region: 'Transition Region / Flare Plasma',
    description: 'The hottest channel \u2014 10 million degrees during flares. This sees the most extreme events in the solar system. Also picks up cooler transition region material.',
    reveals: 'Extreme flare temperatures, hot flux ropes, transition region',
    ion: 'Fe VIII, Fe XXI',
  },
];

// Default observation date - Solar max with visible active region
export const DEFAULT_DATE = '2024-05-10T18:00:00Z';

// Image size in pixels
export const IMAGE_SIZE = 1024;
