// ===========================================
// THE PERMISSIBLE UNIVERSE - EPOCHS
// ===========================================

import { Epoch, DominationEra, DominationType } from './types'
import { EPOCH_COLORS } from './constants'

export const EPOCH_LIST: Epoch[] = [
  {
    id: 'planck',
    name: 'Planck Epoch',
    shortName: 'Planck',
    timeAfterBigBang: '0 - 10⁻⁴³ s',
    logTime: -43,
    temperature: '10³² K',
    logTemperature: 32,
    energy: '10¹⁹ GeV',
    logEnergy: 19,
    logRadiusIntercept: -33,
    description: 'All four forces unified. Quantum gravity dominates. Space-time itself may be quantized.',
    keyEvents: ['All forces unified', 'Quantum gravity era', 'Spacetime foam'],
    dominantPhysics: 'Quantum gravity (unknown)',
    particlesPresent: ['Unknown – current physics breaks down'],
    color: EPOCH_COLORS.planck,
    labelPosition: { logR: -30, logM: -5 },
  },
  {
    id: 'gut',
    name: 'Grand Unification Epoch',
    shortName: 'GUT',
    timeAfterBigBang: '10⁻⁴³ - 10⁻³⁶ s',
    logTime: -36,
    temperature: '10²⁷ K',
    logTemperature: 27,
    energy: '10¹⁶ GeV',
    logEnergy: 16,
    logRadiusIntercept: -28,
    description: 'Gravity separates. Strong, weak, and electromagnetic forces remain unified.',
    keyEvents: ['Gravity separates', 'GUT symmetry', 'Possible inflation trigger'],
    dominantPhysics: 'Grand unified theory',
    particlesPresent: ['X and Y bosons', 'Quarks and leptons interchangeable'],
    color: EPOCH_COLORS.gut,
    labelPosition: { logR: -25, logM: 0 },
  },
  {
    id: 'electroweak',
    name: 'Electroweak Epoch',
    shortName: 'EW',
    timeAfterBigBang: '10⁻³⁶ - 10⁻¹² s',
    logTime: -12,
    temperature: '10¹⁵ K',
    logTemperature: 15,
    energy: '100 GeV',
    logEnergy: 2,
    logRadiusIntercept: -20,
    description: 'Strong force separates. Electromagnetic and weak forces still unified.',
    keyEvents: ['Strong force separates', 'Quark-gluon plasma', 'Higgs field forms'],
    dominantPhysics: 'Electroweak unification',
    particlesPresent: ['Quarks', 'Leptons', 'W, Z, photon (unified)'],
    color: EPOCH_COLORS.electroweak,
    labelPosition: { logR: -18, logM: 5 },
  },
  {
    id: 'nuclear',
    name: 'Nuclear Epoch',
    shortName: 'Nuclear',
    timeAfterBigBang: '1 s - 3 min',
    logTime: 2,
    temperature: '10⁹ K',
    logTemperature: 9,
    energy: '1 MeV',
    logEnergy: -3,
    logRadiusIntercept: -5,
    description: 'Protons and neutrons combine to form nuclei. Big Bang nucleosynthesis.',
    keyEvents: ['Protons and neutrons form', 'Deuterium, helium nuclei', 'Li, Be created'],
    dominantPhysics: 'Nuclear physics',
    particlesPresent: ['Protons', 'Neutrons', 'Electrons', 'Photons', 'Neutrinos'],
    color: EPOCH_COLORS.nuclear,
    labelPosition: { logR: -3, logM: 10 },
  },
  {
    id: 'recombination',
    name: 'Recombination',
    shortName: 'CMB',
    timeAfterBigBang: '380,000 years',
    logTime: 13,
    temperature: '3000 K',
    logTemperature: 3.5,
    energy: '0.3 eV',
    logEnergy: -9.5,
    logRadiusIntercept: 5,
    description: 'Electrons bind to nuclei forming atoms. Universe becomes transparent. CMB released.',
    keyEvents: ['First atoms form', 'Universe becomes transparent', 'CMB released'],
    dominantPhysics: 'Atomic physics',
    particlesPresent: ['Hydrogen atoms', 'Helium atoms', 'Photons'],
    color: EPOCH_COLORS.recombination,
    labelPosition: { logR: 8, logM: 15 },
  },
  {
    id: 'now',
    name: 'Present Era',
    shortName: 'Now',
    timeAfterBigBang: '13.8 billion years',
    logTime: 17.6,
    temperature: '2.7 K',
    logTemperature: 0.4,
    energy: '0.00023 eV',
    logEnergy: -13,
    logRadiusIntercept: 15,
    description: 'Stars, galaxies, planets, and life. Dark energy begins to dominate.',
    keyEvents: ['Stars and galaxies', 'Heavy elements', 'Planets and life'],
    dominantPhysics: 'Standard Model + General Relativity',
    particlesPresent: ['All stable particles', 'Atoms', 'Molecules', 'Dark matter'],
    color: EPOCH_COLORS.now,
    labelPosition: { logR: 18, logM: 20 },
  },
]

export const DOMINATION_LIST: DominationEra[] = [
  {
    id: 'planckian',
    name: 'Planckian',
    symbol: 'Ω_Λᵢ',
    region: [[-40, -45], [-33, -45], [-33, -5], [-40, -5]],
    color: 'rgba(107, 114, 128, 0.2)',
    description: 'Quantum gravity era',
    endTime: '10⁻⁴³ s',
  },
  {
    id: 'radiation',
    name: 'Radiation Dominated',
    symbol: 'Ω_r',
    region: [[-33, -5], [5, -5], [5, 45], [-33, 45]],
    color: 'rgba(239, 68, 68, 0.1)',
    description: 'Photons and relativistic particles dominate energy density',
    startTime: '10⁻⁴³ s',
    endTime: '47,000 years',
  },
  {
    id: 'matter',
    name: 'Matter Dominated',
    symbol: 'Ω_m',
    region: [[5, 20], [25, 20], [25, 55], [5, 55]],
    color: 'rgba(59, 130, 246, 0.1)',
    description: 'Non-relativistic matter dominates',
    startTime: '47,000 years',
    endTime: '9.8 billion years',
  },
  {
    id: 'dark-energy',
    name: 'Dark Energy Dominated',
    symbol: 'Ω_Λ',
    region: [[25, 45], [50, 45], [50, 65], [25, 65]],
    color: 'rgba(209, 213, 219, 0.15)',
    description: 'Accelerating expansion',
    startTime: '9.8 billion years',
  },
]
