// Space Mission Timeline - Curated Dataset
// ~130 significant missions from 1957 to 2025

export type Destination =
  | 'earth-orbit'
  | 'moon'
  | 'venus'
  | 'mars'
  | 'mercury'
  | 'jupiter'
  | 'saturn'
  | 'outer'
  | 'interstellar'
  | 'sun'
  | 'asteroid'
  | 'comet'

export type Outcome = 'success' | 'partial' | 'failure'

export interface Mission {
  id: string
  name: string
  agency: string
  launchDate: string // YYYY-MM-DD
  destination: Destination
  outcome: Outcome
  description: string
  story?: string
  landmark: boolean
}

export const DESTINATION_LABELS: Record<Destination, string> = {
  'earth-orbit': 'Earth Orbit',
  moon: 'Moon',
  venus: 'Venus',
  mars: 'Mars',
  mercury: 'Mercury',
  jupiter: 'Jupiter',
  saturn: 'Saturn',
  outer: 'Outer Solar System',
  interstellar: 'Interstellar',
  sun: 'Sun',
  asteroid: 'Asteroid',
  comet: 'Comet',
}

export const DESTINATION_COLOURS: Record<Destination, string> = {
  'earth-orbit': '#4A90D9',
  moon: '#C0C0C0',
  venus: '#DAA520',
  mars: '#CD4F39',
  mercury: '#A0A0A0',
  jupiter: '#D4A017',
  saturn: '#EEE8AA',
  outer: '#ADD8E6',
  interstellar: '#FFFFFF',
  sun: '#FF8C00',
  asteroid: '#B8956A',
  comet: '#B0E0E6',
}

export const AGENCIES = [
  'NASA',
  'Soviet',
  'ESA',
  'JAXA',
  'CNSA',
  'ISRO',
  'Roscosmos',
  'SpaceIL',
  'KARI',
  'UAESA',
] as const

export const DECADES = [
  '1950s', '1960s', '1970s', '1980s', '1990s', '2000s', '2010s', '2020s',
] as const

export function getDecade(date: string): string {
  const year = parseInt(date.substring(0, 4))
  const decadeStart = Math.floor(year / 10) * 10
  return `${decadeStart}s`
}

export function getYear(date: string): number {
  return parseInt(date.substring(0, 4))
}

export const MISSIONS: Mission[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // 1957-1959: The Space Age Begins
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sputnik-1',
    name: 'Sputnik 1',
    agency: 'Soviet',
    launchDate: '1957-10-04',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First artificial satellite. A polished metal sphere that beeped its way into history and started the Space Age.',
    story: 'On 4 October 1957, a 58-centimetre aluminium sphere was launched from Kazakhstan. It carried no instruments beyond a radio transmitter, but its steady beep-beep-beep, audible to anyone with a shortwave radio, announced that the Soviet Union had put humanity\'s first object into orbit. The shock was felt most acutely in Washington. Within a year, the United States had created NASA.',
    landmark: true,
  },
  {
    id: 'explorer-1',
    name: 'Explorer 1',
    agency: 'NASA',
    launchDate: '1958-02-01',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First US satellite. Discovered the Van Allen radiation belts - the first scientific discovery made from space.',
    story: 'America\'s answer to Sputnik was not just a political statement but a genuine scientific instrument. James Van Allen\'s Geiger counter aboard Explorer 1 detected bands of intense radiation trapped by Earth\'s magnetic field. The Van Allen belts were the first discovery of the Space Age, and they were found not by looking outward, but by looking at our own planet from above.',
    landmark: true,
  },
  {
    id: 'luna-1',
    name: 'Luna 1',
    agency: 'Soviet',
    launchDate: '1959-01-02',
    destination: 'moon',
    outcome: 'partial',
    description: 'First spacecraft to reach the vicinity of the Moon. Missed its target but became the first artificial object in heliocentric orbit.',
    landmark: false,
  },
  {
    id: 'luna-2',
    name: 'Luna 2',
    agency: 'Soviet',
    launchDate: '1959-09-12',
    destination: 'moon',
    outcome: 'success',
    description: 'First spacecraft to reach the surface of another celestial body, impacting the Moon east of Mare Imbrium.',
    landmark: false,
  },
  {
    id: 'luna-3',
    name: 'Luna 3',
    agency: 'Soviet',
    launchDate: '1959-10-04',
    destination: 'moon',
    outcome: 'success',
    description: 'First photographs of the far side of the Moon - the side no human eye had ever seen.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 1960-1969: The Space Race
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'vostok-1',
    name: 'Vostok 1',
    agency: 'Soviet',
    launchDate: '1961-04-12',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Yuri Gagarin became the first human in space, completing one orbit of Earth in 108 minutes.',
    story: 'At 09:07 Moscow time on 12 April 1961, a 27-year-old Soviet pilot named Yuri Gagarin was launched into orbit. He saw the Earth from space for the first time in human history and reportedly said, "The Earth is blue. How wonderful. It is amazing." The entire flight lasted 108 minutes. Gagarin ejected from the capsule at 7 km altitude and parachuted to a field near Saratov, where a farmer and her daughter were the first to find him.',
    landmark: true,
  },
  {
    id: 'mercury-atlas-6',
    name: 'Mercury-Atlas 6 (Friendship 7)',
    agency: 'NASA',
    launchDate: '1962-02-20',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'John Glenn became the first American to orbit Earth, completing three orbits in just under five hours.',
    landmark: true,
  },
  {
    id: 'mariner-2',
    name: 'Mariner 2',
    agency: 'NASA',
    launchDate: '1962-08-27',
    destination: 'venus',
    outcome: 'success',
    description: 'First successful planetary flyby. Confirmed Venus\'s extreme surface temperature and the absence of a strong magnetic field.',
    story: 'Mariner 2 flew within 35,000 km of Venus on 14 December 1962 and confirmed what radio astronomers had suspected: Venus was furnace-hot. Its microwave radiometer measured surface temperatures of around 425°C. The romantic notion of Venus as Earth\'s tropical twin died that day. It was the first time a spacecraft had successfully encountered another planet.',
    landmark: true,
  },
  {
    id: 'vostok-6',
    name: 'Vostok 6',
    agency: 'Soviet',
    launchDate: '1963-06-16',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Valentina Tereshkova became the first woman in space, orbiting Earth 48 times over nearly three days.',
    landmark: false,
  },
  {
    id: 'mariner-4',
    name: 'Mariner 4',
    agency: 'NASA',
    launchDate: '1964-11-28',
    destination: 'mars',
    outcome: 'success',
    description: 'First successful flyby of Mars. Returned 22 close-up photographs showing a cratered, apparently lifeless surface.',
    story: 'When Mariner 4\'s 22 photographs arrived in July 1965, they shattered decades of speculation about Mars. Instead of canals and vegetation, the images showed a cratered, Moon-like desert. Mars was not the living world science fiction had promised. But this disappointment would eventually give way to the discovery of ancient river valleys and the possibility that Mars was once very different.',
    landmark: true,
  },
  {
    id: 'voskhod-2',
    name: 'Voskhod 2',
    agency: 'Soviet',
    launchDate: '1965-03-18',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Alexei Leonov performed the first spacewalk - 12 minutes outside the capsule, nearly unable to return when his suit inflated.',
    landmark: true,
  },
  {
    id: 'gemini-4',
    name: 'Gemini 4',
    agency: 'NASA',
    launchDate: '1965-06-03',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Ed White performed the first American spacewalk during this four-day mission.',
    landmark: false,
  },
  {
    id: 'luna-9',
    name: 'Luna 9',
    agency: 'Soviet',
    launchDate: '1966-01-31',
    destination: 'moon',
    outcome: 'success',
    description: 'First spacecraft to achieve a soft landing on the Moon. Returned the first photographs from the lunar surface.',
    landmark: false,
  },
  {
    id: 'surveyor-1',
    name: 'Surveyor 1',
    agency: 'NASA',
    launchDate: '1966-05-30',
    destination: 'moon',
    outcome: 'success',
    description: 'First American spacecraft to achieve a soft landing on the Moon, proving the surface could support a lander.',
    landmark: false,
  },
  {
    id: 'lunar-orbiter-1',
    name: 'Lunar Orbiter 1',
    agency: 'NASA',
    launchDate: '1966-08-10',
    destination: 'moon',
    outcome: 'success',
    description: 'First US spacecraft to orbit the Moon. Photographed potential Apollo landing sites and captured the first photo of Earth from lunar orbit.',
    landmark: false,
  },
  {
    id: 'venera-4',
    name: 'Venera 4',
    agency: 'Soviet',
    launchDate: '1967-06-12',
    destination: 'venus',
    outcome: 'partial',
    description: 'First spacecraft to transmit data from within the atmosphere of another planet. Crushed by pressure before reaching the surface.',
    landmark: false,
  },
  {
    id: 'apollo-8',
    name: 'Apollo 8',
    agency: 'NASA',
    launchDate: '1968-12-21',
    destination: 'moon',
    outcome: 'success',
    description: 'First crewed spacecraft to leave Earth orbit, reach the Moon, orbit it, and return safely. Gave us the "Earthrise" photograph.',
    story: 'On Christmas Eve 1968, Frank Borman, Jim Lovell, and Bill Anders became the first humans to see the far side of the Moon with their own eyes. But the most significant moment came when they turned around and saw Earth rising above the lunar horizon. Anders\' photograph - "Earthrise" - became one of the most influential images ever taken, widely credited with catalysing the environmental movement.',
    landmark: true,
  },
  {
    id: 'apollo-11',
    name: 'Apollo 11',
    agency: 'NASA',
    launchDate: '1969-07-16',
    destination: 'moon',
    outcome: 'success',
    description: 'First humans to walk on the Moon. Neil Armstrong and Buzz Aldrin spent 2 hours 31 minutes on the lunar surface.',
    story: 'At 20:17 UTC on 20 July 1969, the Eagle lunar module landed in the Sea of Tranquillity with less than 25 seconds of fuel remaining. Six hours later, Neil Armstrong stepped onto the surface. An estimated 600 million people watched on television - the largest audience in history at that time. In total, Armstrong and Aldrin spent just 21 hours on the Moon. They left behind a plaque reading: "We came in peace for all mankind."',
    landmark: true,
  },
  {
    id: 'apollo-12',
    name: 'Apollo 12',
    agency: 'NASA',
    launchDate: '1969-11-14',
    destination: 'moon',
    outcome: 'success',
    description: 'Second crewed Moon landing. Demonstrated precision landing by touching down within walking distance of Surveyor 3.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 1970-1979: Exploration
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'apollo-13',
    name: 'Apollo 13',
    agency: 'NASA',
    launchDate: '1970-04-11',
    destination: 'moon',
    outcome: 'partial',
    description: 'An oxygen tank explosion aborted the lunar landing. The crew survived through improvisation, making it the most famous "successful failure" in spaceflight.',
    story: 'Two days into the mission, an oxygen tank in the service module exploded, crippling the spacecraft. The Moon landing was abandoned. The crew - Jim Lovell, Jack Swigert, and Fred Haise - used the lunar module as a lifeboat, swinging around the Moon and enduring freezing temperatures and dwindling supplies for four days. The ground team improvised solutions in real time, including a carbon dioxide scrubber built from duct tape and cardboard. All three astronauts returned safely.',
    landmark: true,
  },
  {
    id: 'luna-16',
    name: 'Luna 16',
    agency: 'Soviet',
    launchDate: '1970-09-12',
    destination: 'moon',
    outcome: 'success',
    description: 'First robotic mission to return lunar samples to Earth - 101 grams of Moon dust from Mare Fecunditatis.',
    landmark: false,
  },
  {
    id: 'venera-7',
    name: 'Venera 7',
    agency: 'Soviet',
    launchDate: '1970-08-17',
    destination: 'venus',
    outcome: 'partial',
    description: 'First spacecraft to successfully transmit data from the surface of another planet. Survived 23 minutes on Venus.',
    landmark: false,
  },
  {
    id: 'apollo-14',
    name: 'Apollo 14',
    agency: 'NASA',
    launchDate: '1971-01-31',
    destination: 'moon',
    outcome: 'success',
    description: 'Third crewed Moon landing. Alan Shepard famously hit two golf balls on the lunar surface.',
    landmark: false,
  },
  {
    id: 'mariner-9',
    name: 'Mariner 9',
    agency: 'NASA',
    launchDate: '1971-05-30',
    destination: 'mars',
    outcome: 'success',
    description: 'First spacecraft to orbit another planet. Discovered Olympus Mons, Valles Marineris, and evidence of ancient water erosion on Mars.',
    story: 'When Mariner 9 arrived at Mars in November 1971, the entire planet was engulfed in a global dust storm. As the dust settled over the following weeks, the spacecraft revealed a world far more dramatic than Mariner 4\'s cratered desert had suggested. Olympus Mons - the largest volcano in the solar system - emerged from the haze. Then came Valles Marineris, a canyon system that would stretch across the entire continental United States. Mars was not dead - it had simply been hiding its most spectacular features.',
    landmark: true,
  },
  {
    id: 'apollo-15',
    name: 'Apollo 15',
    agency: 'NASA',
    launchDate: '1971-07-26',
    destination: 'moon',
    outcome: 'success',
    description: 'First mission to use the Lunar Roving Vehicle, extending exploration range. David Scott dropped a hammer and feather to demonstrate Galileo\'s principle.',
    landmark: false,
  },
  {
    id: 'pioneer-10',
    name: 'Pioneer 10',
    agency: 'NASA',
    launchDate: '1972-03-03',
    destination: 'jupiter',
    outcome: 'success',
    description: 'First spacecraft to traverse the asteroid belt and make a close flyby of Jupiter. Carries a gold plaque depicting humans and Earth\'s location.',
    story: 'Pioneer 10 was the first spacecraft to venture beyond the asteroid belt - a region many feared would destroy any spacecraft that tried to cross it. It survived, reached Jupiter in December 1973, and returned the first close-up images of the giant planet. The spacecraft carries a gold-anodised aluminium plaque designed by Carl Sagan and Frank Drake, showing a man and woman, a diagram of the solar system, and a map of Earth\'s position relative to 14 pulsars. It is still travelling away from the Sun, though contact was lost in 2003.',
    landmark: true,
  },
  {
    id: 'apollo-17',
    name: 'Apollo 17',
    agency: 'NASA',
    launchDate: '1972-12-07',
    destination: 'moon',
    outcome: 'success',
    description: 'Last crewed mission to the Moon (as of 2025). Eugene Cernan remains the last person to have walked on the lunar surface.',
    landmark: false,
  },
  {
    id: 'mariner-10',
    name: 'Mariner 10',
    agency: 'NASA',
    launchDate: '1973-11-03',
    destination: 'mercury',
    outcome: 'success',
    description: 'First spacecraft to visit Mercury and first to use a gravitational slingshot (Venus) to reach another planet.',
    landmark: false,
  },
  {
    id: 'skylab',
    name: 'Skylab',
    agency: 'NASA',
    launchDate: '1973-05-14',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'America\'s first space station. Three crews occupied it between 1973 and 1974, conducting solar and medical experiments.',
    landmark: false,
  },
  {
    id: 'venera-9',
    name: 'Venera 9',
    agency: 'Soviet',
    launchDate: '1975-06-08',
    destination: 'venus',
    outcome: 'success',
    description: 'First spacecraft to return photographs from the surface of another planet. Showed a rocky landscape under an orange sky.',
    landmark: false,
  },
  {
    id: 'viking-1',
    name: 'Viking 1',
    agency: 'NASA',
    launchDate: '1975-08-20',
    destination: 'mars',
    outcome: 'success',
    description: 'First successful Mars lander. Operated for over six years, returning the first photographs from the Martian surface and conducting the first soil experiments.',
    story: 'Viking 1 landed on Chryse Planitia on 20 July 1976 - exactly seven years after Apollo 11. Its cameras revealed a rust-coloured desert strewn with rocks under a pink sky. The lander\'s biology experiments produced ambiguous results that are still debated today. Was there life in the Martian soil? The Viking results were officially interpreted as negative, but some scientists have never accepted that conclusion. Viking proved Mars could be reached and studied on the surface - and raised questions we are still trying to answer.',
    landmark: true,
  },
  {
    id: 'viking-2',
    name: 'Viking 2',
    agency: 'NASA',
    launchDate: '1975-09-09',
    destination: 'mars',
    outcome: 'success',
    description: 'Second Mars lander, touching down at Utopia Planitia. Operated for over three years on the surface.',
    landmark: false,
  },
  {
    id: 'voyager-2',
    name: 'Voyager 2',
    agency: 'NASA',
    launchDate: '1977-08-20',
    destination: 'outer',
    outcome: 'success',
    description: 'The only spacecraft to have visited all four giant planets: Jupiter, Saturn, Uranus, and Neptune. Still transmitting from interstellar space.',
    story: 'Voyager 2 launched sixteen days before its twin but followed a slower trajectory. What made it unique was its grand tour - a planetary alignment that occurs once every 175 years allowed it to visit Jupiter (1979), Saturn (1981), Uranus (1986), and Neptune (1989). At each encounter, it made discoveries: volcanic eruptions on Jupiter\'s moon Io, the braided structure of Saturn\'s rings, the tilted magnetic field of Uranus, and the supersonic winds of Neptune. No other spacecraft has visited Uranus or Neptune. In 2018, Voyager 2 crossed into interstellar space and is still sending data back to Earth.',
    landmark: true,
  },
  {
    id: 'voyager-1',
    name: 'Voyager 1',
    agency: 'NASA',
    launchDate: '1977-09-05',
    destination: 'interstellar',
    outcome: 'success',
    description: 'The most distant human-made object. Visited Jupiter and Saturn before heading for the stars, carrying the Golden Record.',
    story: 'Each Voyager carries a golden phonograph record containing 115 images, natural sounds, music from many cultures, and greetings in 55 languages. Carl Sagan chaired the committee that selected the contents. "The spacecraft will be encountered and the record played only if there are advanced spacefaring civilisations in interstellar space," Sagan wrote. "But the launching of this bottle into the cosmic ocean says something very hopeful about life on this planet." In 2012, Voyager 1 became the first human-made object to enter interstellar space, 35 years after launch. It is still transmitting.',
    landmark: true,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 1980-1989: Shuttle Era
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'sts-1',
    name: 'STS-1 (Columbia)',
    agency: 'NASA',
    launchDate: '1981-04-12',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First flight of the Space Shuttle - the world\'s first reusable crewed spacecraft. Launched exactly 20 years after Gagarin.',
    story: 'The Space Shuttle was unlike anything that had flown before: a winged orbiter that launched like a rocket and landed like an aeroplane. STS-1 launched on 12 April 1981, twenty years to the day after Vostok 1. Astronauts John Young and Robert Crippen orbited Earth 36 times over two days before gliding to a landing at Edwards Air Force Base. The shuttle programme would fly 135 missions over 30 years, building the International Space Station and launching the Hubble Space Telescope.',
    landmark: true,
  },
  {
    id: 'venera-13',
    name: 'Venera 13',
    agency: 'Soviet',
    launchDate: '1981-10-30',
    destination: 'venus',
    outcome: 'success',
    description: 'Returned the first colour photographs from the surface of Venus and analysed soil composition. Survived 127 minutes at 457°C.',
    landmark: false,
  },
  {
    id: 'sts-7',
    name: 'STS-7',
    agency: 'NASA',
    launchDate: '1983-06-18',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Sally Ride became the first American woman in space aboard the shuttle Challenger.',
    landmark: false,
  },
  {
    id: 'vega-1',
    name: 'Vega 1',
    agency: 'Soviet',
    launchDate: '1984-12-15',
    destination: 'venus',
    outcome: 'success',
    description: 'Dual mission: dropped a lander and balloon at Venus, then flew on to make a close encounter with Halley\'s Comet.',
    landmark: false,
  },
  {
    id: 'sts-51l',
    name: 'STS-51-L (Challenger)',
    agency: 'NASA',
    launchDate: '1986-01-28',
    destination: 'earth-orbit',
    outcome: 'failure',
    description: 'The space shuttle Challenger broke apart 73 seconds after launch, killing all seven crew members including teacher Christa McAuliffe.',
    story: 'On a bitterly cold Florida morning, the space shuttle Challenger launched despite concerns about the effect of low temperatures on its solid rocket booster O-rings. 73 seconds into flight, a plume of flame from the right booster breached the external fuel tank. The shuttle broke apart at an altitude of 14.6 km. All seven crew members were killed, including Christa McAuliffe, who had been selected from 11,000 applicants to be the first teacher in space. The disaster grounded the shuttle fleet for nearly three years and led to fundamental changes in NASA\'s safety culture.',
    landmark: true,
  },
  {
    id: 'giotto',
    name: 'Giotto',
    agency: 'ESA',
    launchDate: '1985-07-02',
    destination: 'comet',
    outcome: 'success',
    description: 'First close encounter with a comet nucleus. Flew within 596 km of Halley\'s Comet, returning the first images of a comet\'s core.',
    landmark: false,
  },
  {
    id: 'mir',
    name: 'Mir',
    agency: 'Soviet',
    launchDate: '1986-02-20',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First modular space station. Continuously occupied for nearly ten years, hosting crews from multiple nations.',
    landmark: false,
  },
  {
    id: 'magellan',
    name: 'Magellan',
    agency: 'NASA',
    launchDate: '1989-05-04',
    destination: 'venus',
    outcome: 'success',
    description: 'Mapped 98% of Venus\'s surface using synthetic aperture radar, revealing a landscape of volcanoes, lava plains, and impact craters.',
    landmark: false,
  },
  {
    id: 'galileo',
    name: 'Galileo',
    agency: 'NASA',
    launchDate: '1989-10-18',
    destination: 'jupiter',
    outcome: 'success',
    description: 'First spacecraft to orbit Jupiter and first to deploy a probe into a giant planet\'s atmosphere. Discovered evidence of subsurface oceans on Europa.',
    story: 'Galileo spent eight years orbiting Jupiter, making 34 orbits and repeatedly flying past its four largest moons. Its most consequential discovery was evidence that Europa, Ganymede, and Callisto all harbour subsurface oceans of liquid water beneath their icy crusts. This transformed our understanding of where life might exist in the solar system. In 2003, the spacecraft was deliberately plunged into Jupiter\'s atmosphere to avoid any possibility of contaminating Europa with Earth organisms.',
    landmark: true,
  },
  {
    id: 'voyager-2-neptune',
    name: 'Voyager 2 Neptune Encounter',
    agency: 'NASA',
    launchDate: '1977-08-20',
    destination: 'outer',
    outcome: 'success',
    description: 'Voyager 2\'s final planetary encounter. The only spacecraft to visit Neptune, revealing supersonic winds and the moon Triton\'s geysers.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 1990-1999: Hubble, Mars, and the ISS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'hubble',
    name: 'Hubble Space Telescope',
    agency: 'NASA',
    launchDate: '1990-04-24',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'The most scientifically productive instrument ever built. Transformed our understanding of the universe\'s age, expansion rate, and structure.',
    story: 'Hubble launched with a flawed mirror that produced blurry images - an embarrassment that nearly ended the programme. In 1993, astronauts installed corrective optics during a shuttle servicing mission, and Hubble became the most powerful eye humanity had ever turned on the cosmos. Its deep field images revealed thousands of galaxies in a patch of sky the size of a grain of sand held at arm\'s length. It measured the expansion rate of the universe, helped discover dark energy, and photographed stellar nurseries, dying stars, and colliding galaxies with unprecedented clarity.',
    landmark: true,
  },
  {
    id: 'ulysses',
    name: 'Ulysses',
    agency: 'ESA',
    launchDate: '1990-10-06',
    destination: 'sun',
    outcome: 'success',
    description: 'First spacecraft to fly over the poles of the Sun, using a Jupiter gravity assist to leave the ecliptic plane.',
    landmark: false,
  },
  {
    id: 'mars-observer',
    name: 'Mars Observer',
    agency: 'NASA',
    launchDate: '1992-09-25',
    destination: 'mars',
    outcome: 'failure',
    description: 'Contact lost three days before entering Mars orbit. The failure prompted NASA to adopt a "faster, better, cheaper" approach.',
    landmark: false,
  },
  {
    id: 'clementine',
    name: 'Clementine',
    agency: 'NASA',
    launchDate: '1994-01-25',
    destination: 'moon',
    outcome: 'success',
    description: 'First mission to map the entire lunar surface in multiple wavelengths. Found indirect evidence of water ice in permanently shadowed craters.',
    landmark: false,
  },
  {
    id: 'near-shoemaker',
    name: 'NEAR Shoemaker',
    agency: 'NASA',
    launchDate: '1996-02-17',
    destination: 'asteroid',
    outcome: 'success',
    description: 'First spacecraft to orbit an asteroid (433 Eros) and first to land on one, despite not being designed for landing.',
    landmark: false,
  },
  {
    id: 'mars-global-surveyor',
    name: 'Mars Global Surveyor',
    agency: 'NASA',
    launchDate: '1996-11-07',
    destination: 'mars',
    outcome: 'success',
    description: 'Mapped the entire Martian surface in high resolution. Discovered evidence of recent liquid water activity on the surface.',
    landmark: false,
  },
  {
    id: 'mars-pathfinder',
    name: 'Mars Pathfinder',
    agency: 'NASA',
    launchDate: '1996-12-04',
    destination: 'mars',
    outcome: 'success',
    description: 'Deployed Sojourner, the first rover to operate on Mars. Proved that low-cost Mars landings were possible.',
    story: 'Mars Pathfinder bounced to a landing on the Fourth of July 1997, cushioned by giant airbags. It deployed a microwave-oven-sized rover called Sojourner that trundled across the Martian surface for 83 days, analysing rocks with names like Barnacle Bill and Yogi. The mission proved that NASA could reach Mars for a fraction of what Viking had cost and introduced a new landing technique. Pathfinder generated enormous public interest - its website received 566 million hits in five days, a record at the time.',
    landmark: true,
  },
  {
    id: 'cassini-huygens',
    name: 'Cassini-Huygens',
    agency: 'NASA',
    launchDate: '1997-10-15',
    destination: 'saturn',
    outcome: 'success',
    description: 'Orbited Saturn for 13 years. The Huygens probe made the first landing in the outer solar system, descending through Titan\'s atmosphere.',
    story: 'Cassini arrived at Saturn in 2004 and spent 13 years exploring the ringed planet and its 83 known moons. On Christmas Day 2004, it released the Huygens probe, which parachuted through Titan\'s thick atmosphere and landed on a surface scattered with rounded ice pebbles shaped by liquid methane rivers. Cassini discovered water geysers erupting from the south pole of Enceladus - jets of salty water spraying into space from a subsurface ocean. In 2017, running low on fuel, Cassini was deliberately plunged into Saturn\'s atmosphere to protect the potentially habitable moons from contamination.',
    landmark: true,
  },
  {
    id: 'lunar-prospector',
    name: 'Lunar Prospector',
    agency: 'NASA',
    launchDate: '1998-01-07',
    destination: 'moon',
    outcome: 'success',
    description: 'Confirmed the presence of hydrogen (likely water ice) at the lunar poles and mapped the Moon\'s gravitational field.',
    landmark: false,
  },
  {
    id: 'iss-zarya',
    name: 'ISS Zarya Module',
    agency: 'Roscosmos',
    launchDate: '1998-11-20',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First module of the International Space Station. Beginning of the largest structure ever assembled in space.',
    landmark: false,
  },
  {
    id: 'mars-climate-orbiter',
    name: 'Mars Climate Orbiter',
    agency: 'NASA',
    launchDate: '1998-12-11',
    destination: 'mars',
    outcome: 'failure',
    description: 'Destroyed on arrival at Mars because one team used imperial units and another used metric. The most expensive unit conversion error in history.',
    landmark: false,
  },
  {
    id: 'stardust',
    name: 'Stardust',
    agency: 'NASA',
    launchDate: '1999-02-07',
    destination: 'comet',
    outcome: 'success',
    description: 'First mission to collect dust samples from a comet (Wild 2) and return them to Earth. Found amino acids in the samples.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2000-2009: New Millennium
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'iss-expedition-1',
    name: 'ISS Expedition 1',
    agency: 'NASA',
    launchDate: '2000-10-31',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'First permanent crew aboard the International Space Station. The ISS has been continuously occupied ever since.',
    landmark: false,
  },
  {
    id: 'mars-odyssey',
    name: 'Mars Odyssey',
    agency: 'NASA',
    launchDate: '2001-04-07',
    destination: 'mars',
    outcome: 'success',
    description: 'Longest-serving spacecraft at Mars. Detected vast quantities of subsurface water ice and served as a relay for surface missions.',
    landmark: false,
  },
  {
    id: 'genesis',
    name: 'Genesis',
    agency: 'NASA',
    launchDate: '2001-08-08',
    destination: 'sun',
    outcome: 'partial',
    description: 'Collected solar wind particles for 27 months. The sample return capsule crashed when its parachute failed, but some samples were recovered.',
    landmark: false,
  },
  {
    id: 'sts-107',
    name: 'STS-107 (Columbia)',
    agency: 'NASA',
    launchDate: '2003-01-16',
    destination: 'earth-orbit',
    outcome: 'failure',
    description: 'The space shuttle Columbia broke apart during re-entry, killing all seven crew members. Foam insulation damage during launch breached the wing.',
    landmark: false,
  },
  {
    id: 'mars-express',
    name: 'Mars Express',
    agency: 'ESA',
    launchDate: '2003-06-02',
    destination: 'mars',
    outcome: 'success',
    description: 'Europe\'s first Mars mission. Confirmed water ice at the south pole and found methane in the atmosphere (still debated).',
    landmark: false,
  },
  {
    id: 'spirit',
    name: 'Spirit (MER-A)',
    agency: 'NASA',
    launchDate: '2003-06-10',
    destination: 'mars',
    outcome: 'success',
    description: 'Mars rover designed for 90 days, operated for over six years. Found evidence that Gusev Crater once held standing water.',
    landmark: false,
  },
  {
    id: 'opportunity',
    name: 'Opportunity (MER-B)',
    agency: 'NASA',
    launchDate: '2003-07-08',
    destination: 'mars',
    outcome: 'success',
    description: 'Designed for 90 days, survived for 15 years. Drove 45 km across Mars, confirming ancient water and setting the extraterrestrial driving record.',
    story: 'Opportunity landed in a small crater and immediately found exposed bedrock containing hematite "blueberries" - mineral spheres that form in water. Over the next 15 years, it drove 45.16 km across the Martian surface, the longest distance any off-Earth wheeled vehicle has ever covered. It explored craters, examined meteorites, and documented dust devils. In June 2018, a global dust storm darkened the sky so completely that Opportunity\'s solar panels could not generate enough power. Its last transmission, on 10 June 2018, was interpreted as: "My battery is low and it\'s getting dark."',
    landmark: true,
  },
  {
    id: 'hayabusa',
    name: 'Hayabusa',
    agency: 'JAXA',
    launchDate: '2003-05-09',
    destination: 'asteroid',
    outcome: 'partial',
    description: 'First mission to return samples from an asteroid (25143 Itokawa). Overcame multiple failures to bring back microscopic grains.',
    landmark: false,
  },
  {
    id: 'rosetta',
    name: 'Rosetta',
    agency: 'ESA',
    launchDate: '2004-03-02',
    destination: 'comet',
    outcome: 'success',
    description: 'First spacecraft to orbit a comet and deploy a lander on its surface. Spent two years studying Comet 67P/Churyumov-Gerasimenko.',
    story: 'Rosetta took ten years and four gravity assists (three from Earth, one from Mars) to reach Comet 67P. When it arrived in 2014, the comet was revealed to be a bizarre "rubber duck" shape - two lobes connected by a narrow neck. In November 2014, the Philae lander detached and descended to the surface, but bounced twice before coming to rest in a shadowed crevice where its solar panels could not charge. It transmitted data for 60 hours before falling silent. Rosetta continued orbiting until 2016, discovering organic molecules, monitoring the comet\'s activity as it approached the Sun, and producing the most detailed portrait of a comet ever assembled.',
    landmark: true,
  },
  {
    id: 'messenger',
    name: 'MESSENGER',
    agency: 'NASA',
    launchDate: '2004-08-03',
    destination: 'mercury',
    outcome: 'success',
    description: 'First spacecraft to orbit Mercury. Discovered water ice in permanently shadowed craters at Mercury\'s poles.',
    landmark: false,
  },
  {
    id: 'deep-impact',
    name: 'Deep Impact',
    agency: 'NASA',
    launchDate: '2005-01-12',
    destination: 'comet',
    outcome: 'success',
    description: 'Fired a 370 kg copper impactor into Comet Tempel 1 to study its interior composition. Detected water ice and organic material.',
    landmark: false,
  },
  {
    id: 'mro',
    name: 'Mars Reconnaissance Orbiter',
    agency: 'NASA',
    launchDate: '2005-08-12',
    destination: 'mars',
    outcome: 'success',
    description: 'Carries the most powerful camera ever sent to another planet (HiRISE). Has returned more data than all other Mars missions combined.',
    landmark: false,
  },
  {
    id: 'new-horizons',
    name: 'New Horizons',
    agency: 'NASA',
    launchDate: '2006-01-19',
    destination: 'outer',
    outcome: 'success',
    description: 'First spacecraft to visit Pluto. Revealed a world of nitrogen ice glaciers, mountain ranges of water ice, and a heart-shaped plain.',
    story: 'New Horizons launched at the fastest speed any spacecraft had ever left Earth - 16.26 km/s - and still took nine and a half years to reach Pluto. On 14 July 2015, it flew past the dwarf planet at 49,600 km/h, gathering data frantically during the brief encounter. The images it returned stunned the world: Pluto was not the dead, featureless ice ball everyone had expected. It had towering mountains of water ice, vast plains of nitrogen ice that appeared to be actively convecting, and a thin haze of atmospheric nitrogen. The heart-shaped feature, informally named Tombaugh Regio after Pluto\'s discoverer, became an instant icon.',
    landmark: true,
  },
  {
    id: 'phoenix',
    name: 'Phoenix',
    agency: 'NASA',
    launchDate: '2007-08-04',
    destination: 'mars',
    outcome: 'success',
    description: 'Landed near Mars\'s north pole and confirmed the presence of water ice just below the surface. Observed snow falling in the Martian atmosphere.',
    landmark: false,
  },
  {
    id: 'chandrayaan-1',
    name: 'Chandrayaan-1',
    agency: 'ISRO',
    launchDate: '2008-10-22',
    destination: 'moon',
    outcome: 'partial',
    description: 'India\'s first lunar mission. Confirmed the presence of water molecules on the Moon\'s surface using its Moon Impact Probe.',
    landmark: false,
  },
  {
    id: 'kepler',
    name: 'Kepler Space Telescope',
    agency: 'NASA',
    launchDate: '2009-03-07',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Discovered over 2,600 confirmed exoplanets by monitoring the brightness of 150,000 stars. Showed that planets are common in the galaxy.',
    landmark: false,
  },
  {
    id: 'lcross',
    name: 'LCROSS',
    agency: 'NASA',
    launchDate: '2009-06-18',
    destination: 'moon',
    outcome: 'success',
    description: 'Deliberately crashed into a permanently shadowed lunar crater and confirmed significant quantities of water ice.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2010-2019: Private Space and Robotic Explorers
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'curiosity',
    name: 'Curiosity (MSL)',
    agency: 'NASA',
    launchDate: '2011-11-26',
    destination: 'mars',
    outcome: 'success',
    description: 'Car-sized Mars rover that landed using a sky crane. Found organic molecules and confirmed Gale Crater was once a habitable lake environment.',
    story: 'Curiosity was too heavy for airbags, so NASA invented the sky crane - a rocket-powered descent stage that lowered the rover to the surface on nylon cables before flying away. The "seven minutes of terror" entry, descent, and landing were the most complex ever attempted. Since landing in August 2012, Curiosity has been climbing the central peak of Gale Crater, reading the geological record layer by layer. It has found organic molecules, seasonal methane variations, and definitive evidence that Gale Crater was once a lake of liquid water that could have supported microbial life.',
    landmark: true,
  },
  {
    id: 'juno',
    name: 'Juno',
    agency: 'NASA',
    launchDate: '2011-08-05',
    destination: 'jupiter',
    outcome: 'success',
    description: 'First solar-powered spacecraft at Jupiter. Revealed that Jupiter\'s interior structure is very different from what models predicted.',
    landmark: false,
  },
  {
    id: 'curiosity-landing',
    name: 'Curiosity Landing',
    agency: 'NASA',
    launchDate: '2012-08-06',
    destination: 'mars',
    outcome: 'success',
    description: 'First use of the sky crane landing system. Seven minutes of terror followed by the first colour HD images from Mars.',
    landmark: false,
  },
  {
    id: 'change-3',
    name: 'Chang\'e 3',
    agency: 'CNSA',
    launchDate: '2013-12-01',
    destination: 'moon',
    outcome: 'success',
    description: 'China\'s first lunar lander. Deployed the Yutu rover - the first soft landing on the Moon since Luna 24 in 1976.',
    landmark: false,
  },
  {
    id: 'maven',
    name: 'MAVEN',
    agency: 'NASA',
    launchDate: '2013-11-18',
    destination: 'mars',
    outcome: 'success',
    description: 'Determined that Mars lost most of its atmosphere to solar wind stripping, explaining how the once-wet planet became a cold desert.',
    landmark: false,
  },
  {
    id: 'mangalyaan',
    name: 'Mangalyaan (Mars Orbiter Mission)',
    agency: 'ISRO',
    launchDate: '2013-11-05',
    destination: 'mars',
    outcome: 'success',
    description: 'India\'s first interplanetary mission. Reached Mars on the first attempt - the first space agency to do so. Cost less than the film Gravity.',
    landmark: false,
  },
  {
    id: 'rosetta-landing',
    name: 'Philae Landing on Comet 67P',
    agency: 'ESA',
    launchDate: '2004-03-02',
    destination: 'comet',
    outcome: 'partial',
    description: 'First landing on a comet. Philae bounced twice before settling in a shadowed crevice, transmitting 60 hours of data.',
    landmark: true,
  },
  {
    id: 'new-horizons-pluto',
    name: 'New Horizons Pluto Flyby',
    agency: 'NASA',
    launchDate: '2006-01-19',
    destination: 'outer',
    outcome: 'success',
    description: 'First close encounter with Pluto on 14 July 2015. Revealed a geologically active world with nitrogen glaciers and water ice mountains.',
    landmark: false,
  },
  {
    id: 'lisa-pathfinder',
    name: 'LISA Pathfinder',
    agency: 'ESA',
    launchDate: '2015-12-03',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Technology demonstrator for future gravitational wave detection in space. Exceeded performance requirements by a factor of five.',
    landmark: false,
  },
  {
    id: 'osiris-rex',
    name: 'OSIRIS-REx',
    agency: 'NASA',
    launchDate: '2016-09-08',
    destination: 'asteroid',
    outcome: 'success',
    description: 'Collected 121 grams of material from asteroid Bennu using a touch-and-go manoeuvre and returned the samples to Earth in September 2023.',
    landmark: false,
  },
  {
    id: 'cassini-finale',
    name: 'Cassini Grand Finale',
    agency: 'NASA',
    launchDate: '1997-10-15',
    destination: 'saturn',
    outcome: 'success',
    description: 'After 13 years at Saturn, Cassini dived between the planet and its rings 22 times before plunging into Saturn\'s atmosphere on 15 September 2017.',
    landmark: false,
  },
  {
    id: 'insight',
    name: 'InSight',
    agency: 'NASA',
    launchDate: '2018-05-05',
    destination: 'mars',
    outcome: 'success',
    description: 'First mission to study Mars\'s deep interior. Detected over 1,300 marsquakes and revealed the structure of the Martian core, mantle, and crust.',
    landmark: false,
  },
  {
    id: 'parker-solar-probe',
    name: 'Parker Solar Probe',
    agency: 'NASA',
    launchDate: '2018-08-12',
    destination: 'sun',
    outcome: 'success',
    description: 'Fastest human-made object. Flying through the Sun\'s corona at up to 690,000 km/h, measuring the solar wind at its source.',
    landmark: false,
  },
  {
    id: 'change-4',
    name: 'Chang\'e 4',
    agency: 'CNSA',
    launchDate: '2018-12-07',
    destination: 'moon',
    outcome: 'success',
    description: 'First spacecraft to land on the far side of the Moon. Deployed the Yutu-2 rover, which has been exploring the Von Karman crater.',
    landmark: true,
  },
  {
    id: 'beresheet',
    name: 'Beresheet',
    agency: 'SpaceIL',
    launchDate: '2019-02-22',
    destination: 'moon',
    outcome: 'failure',
    description: 'First privately funded lunar lander. Lost contact during descent and crashed on the Moon, but proved that small nations and private organisations could reach the Moon.',
    landmark: false,
  },
  {
    id: 'hayabusa2-return',
    name: 'Hayabusa2 Sample Return',
    agency: 'JAXA',
    launchDate: '2014-12-03',
    destination: 'asteroid',
    outcome: 'success',
    description: 'Returned 5.4 grams from asteroid Ryugu. Found amino acids and other organic molecules, supporting the theory that life\'s building blocks came from space.',
    landmark: false,
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // 2020-2025: New Era
  // ═══════════════════════════════════════════════════════════════════════════
  {
    id: 'hope',
    name: 'Hope (Al-Amal)',
    agency: 'UAESA',
    launchDate: '2020-07-19',
    destination: 'mars',
    outcome: 'success',
    description: 'UAE\'s first interplanetary mission. Studying Mars\'s atmosphere and weather patterns from orbit.',
    landmark: false,
  },
  {
    id: 'tianwen-1',
    name: 'Tianwen-1',
    agency: 'CNSA',
    launchDate: '2020-07-23',
    destination: 'mars',
    outcome: 'success',
    description: 'China\'s first Mars mission. Successfully deployed the Zhurong rover - making China the second country to operate a rover on Mars.',
    landmark: false,
  },
  {
    id: 'perseverance',
    name: 'Perseverance & Ingenuity',
    agency: 'NASA',
    launchDate: '2020-07-30',
    destination: 'mars',
    outcome: 'success',
    description: 'Most advanced Mars rover ever built. Ingenuity became the first aircraft to fly on another planet, completing 72 flights.',
    story: 'Perseverance landed in Jezero Crater - an ancient river delta - in February 2021. It carried Ingenuity, a 1.8 kg helicopter that was intended as a 30-day technology demonstration. Instead, Ingenuity flew 72 times over three years, scouting ahead for the rover, flying higher and faster with each sortie. It proved that powered, controlled flight was possible in Mars\'s thin atmosphere - opening the door to aerial exploration of other worlds. Meanwhile, Perseverance has been drilling rock cores and caching them on the surface for a future sample return mission that will bring Martian rock to Earth for the first time.',
    landmark: true,
  },
  {
    id: 'jwst',
    name: 'James Webb Space Telescope',
    agency: 'NASA',
    launchDate: '2021-12-25',
    destination: 'earth-orbit',
    outcome: 'success',
    description: 'Largest and most powerful space telescope ever launched. Observing in infrared from the second Lagrange point, 1.5 million km from Earth.',
    story: 'The James Webb Space Telescope was launched on Christmas Day 2021 after decades of development, schedule slips, and cost overruns. Over the following month, it executed 344 single-point-of-failure deployments - any one of which could have ended the mission. All of them worked. Its 6.5-metre gold-coated mirror, six times larger than Hubble\'s, began revealing the universe in infrared light with unprecedented clarity. Its first deep field image, released in July 2022, showed galaxies formed less than 400 million years after the Big Bang. Webb has since studied exoplanet atmospheres, stellar nurseries, and the most distant objects ever observed.',
    landmark: true,
  },
  {
    id: 'dart',
    name: 'DART',
    agency: 'NASA',
    launchDate: '2021-11-24',
    destination: 'asteroid',
    outcome: 'success',
    description: 'First planetary defence test. Deliberately crashed into asteroid Dimorphos and successfully changed its orbit - proving we can deflect a threatening asteroid.',
    story: 'On 26 September 2022, the DART spacecraft slammed into the small asteroid Dimorphos at 6.6 km/s. It was not an accident - it was the first practical test of planetary defence. Dimorphos orbited a larger asteroid called Didymos, and the impact shortened that orbit by 33 minutes, far exceeding the 73-second minimum that would have counted as success. For the first time, humanity had deliberately altered the trajectory of a celestial body. If an asteroid is ever found on a collision course with Earth, we now know that kinetic impact can work.',
    landmark: true,
  },
  {
    id: 'artemis-1',
    name: 'Artemis I',
    agency: 'NASA',
    launchDate: '2022-11-16',
    destination: 'moon',
    outcome: 'success',
    description: 'First flight of the Space Launch System. Sent an uncrewed Orion capsule around the Moon and back, paving the way for crewed lunar return.',
    landmark: false,
  },
  {
    id: 'juice',
    name: 'JUICE',
    agency: 'ESA',
    launchDate: '2023-04-14',
    destination: 'jupiter',
    outcome: 'success',
    description: 'Jupiter Icy Moons Explorer. En route to study Ganymede, Callisto, and Europa, arriving at Jupiter in 2031.',
    landmark: false,
  },
  {
    id: 'chandrayaan-3',
    name: 'Chandrayaan-3',
    agency: 'ISRO',
    launchDate: '2023-07-14',
    destination: 'moon',
    outcome: 'success',
    description: 'India became the fourth country to land on the Moon and the first to land near the lunar south pole. The Pragyan rover confirmed sulphur in the polar regolith.',
    landmark: true,
  },
  {
    id: 'slim',
    name: 'SLIM',
    agency: 'JAXA',
    launchDate: '2023-09-07',
    destination: 'moon',
    outcome: 'partial',
    description: 'Japan\'s Smart Lander for Investigating Moon achieved a pinpoint landing within 55 metres of its target, but landed upside down. Still transmitted data.',
    landmark: false,
  },
  {
    id: 'psyche',
    name: 'Psyche',
    agency: 'NASA',
    launchDate: '2023-10-13',
    destination: 'asteroid',
    outcome: 'success',
    description: 'En route to asteroid 16 Psyche, believed to be the exposed iron core of a protoplanet. Will arrive in 2029.',
    landmark: false,
  },
  {
    id: 'im-1',
    name: 'IM-1 Odysseus',
    agency: 'NASA',
    launchDate: '2024-02-15',
    destination: 'moon',
    outcome: 'partial',
    description: 'First commercial lunar lander (Intuitive Machines). Landed near the south pole but tipped on its side. Still transmitted data for seven days.',
    landmark: false,
  },
  {
    id: 'europa-clipper',
    name: 'Europa Clipper',
    agency: 'NASA',
    launchDate: '2024-10-14',
    destination: 'jupiter',
    outcome: 'success',
    description: 'Largest spacecraft NASA has ever built for a planetary mission. Will perform 49 flybys of Europa to study its subsurface ocean and assess habitability.',
    landmark: true,
  },
  {
    id: 'change-6',
    name: 'Chang\'e 6',
    agency: 'CNSA',
    launchDate: '2024-05-03',
    destination: 'moon',
    outcome: 'success',
    description: 'First mission to return samples from the far side of the Moon. Collected 1,935 grams of lunar material from the Apollo basin.',
    landmark: false,
  },
  {
    id: 'hera',
    name: 'Hera',
    agency: 'ESA',
    launchDate: '2024-10-07',
    destination: 'asteroid',
    outcome: 'success',
    description: 'Follow-up to DART. En route to survey the Didymos-Dimorphos system and study the crater and orbital change left by the DART impact.',
    landmark: false,
  },
]

// ─── Helper functions ───────────────────────────────────────────────────────

export function getMissionsByDecade(missions: Mission[]): { decade: string; missions: Mission[] }[] {
  const decadeMap = new Map<string, Mission[]>()

  for (const mission of missions) {
    const decade = getDecade(mission.launchDate)
    if (!decadeMap.has(decade)) {
      decadeMap.set(decade, [])
    }
    decadeMap.get(decade)!.push(mission)
  }

  // Sort decades chronologically
  const sorted = Array.from(decadeMap.entries()).sort(([a], [b]) => a.localeCompare(b))

  return sorted.map(([decade, missions]) => ({
    decade,
    missions: missions.sort(
      (a, b) => new Date(a.launchDate).getTime() - new Date(b.launchDate).getTime()
    ),
  }))
}

export function getUniqueAgencies(missions: Mission[]): string[] {
  return Array.from(new Set(missions.map(m => m.agency))).sort()
}

export function getUniqueDestinations(missions: Mission[]): Destination[] {
  return Array.from(new Set(missions.map(m => m.destination))).sort()
}
